### ISSUE TITLE
Could we just save .mht files from URL directly ?

### ISSUE THREAD

**Issue by 276562578** [scooby/mhtml_unpack#1]
It's easier, I think. It's better we can use it like a library in my progress. Thanks anyway

**Comment by scooby** [comment]
You can do that already if you use it as a library. The script functionality is entirely provided under the `if __name__ == '__main__'`, so you could use this as a library without any modification.

If you notice [this line](https://github.com/scooby/mhtml_unpack/blob/master/mht_unpack.py#L338), the script is just constructing the message object using `email.message_from_binary_file()`. You could load the file into a bytes buffer and use `email.message_from_bytes()`to pass a message object into your preferred constructor, again, see the script for how it's done.

**Comment by 276562578** [comment]
So, that means i can use email.message_from_bytes() to download page directly form url address like 'http://www.google.com' rather than file ?

**Comment by scooby** [comment]
Sorry, at this point you're getting into basic questions about how to write Python code. Please consult [the Python docs](https://docs.python.org/3/) or a resource like stackoverflow.

**Comment by 276562578** [comment]
Sorry, my fault. Actually It's save to .mht directly form url address like 'http://www.google.com' rather than file ?

**Comment by 276562578** [comment]
Sorry for these simple question. Thanks for your answer.

**Comment by scooby** [comment]
"How do I learn Python" is an important question, it's just a github issue is a lousy way to get the answers. The docs are far better written than any guidance I could give you.
